name: Download latest cards.json, create json for each lang, and commit

on:
  schedule:
    - cron:  '30 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'
      - name: Install Dependencies (using package-lock.json)
        run: npm ci
      - name: Download latest cards.json (If-Modified-Since) and create json for each lang
        run: npm run build-compileifneeded
      - uses: stefanzweifel/git-auto-commit-action@v5
